//cart action
export const GET_LIST_CART = "GET_LIST_CART";
export const GET_LIST_CART_SUCCESS = "GET_LIST_CART_SUCCESS";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const ADD_PRODUCT_TO_CART_SUCCESS = "ADD_PRODUCT_TO_CART_SUCCESS";

export const DELETE_PRODUCT_TO_CART = "DELETE_PRODUCT_TO_CART";
export const DELETE_PRODUCT_TO_CART_SUCCESS = "DELETE_PRODUCT_TO_CART_SUCCESS";

export const UPDATE_PRODUCT_TO_CART = "UPDATE_PRODUCT_TO_CART";
export const UPDATE_PRODUCT_TO_CART_SUCCESS = "UPDATE_PRODUCT_TO_CART_SUCCESS";

export const IS_PRODUCT_BOUGHT = "IS_PRODUCT_BOUGHT";
export const CLEAR_IS_PRODUCT_BOUGHT = "CLEAR_IS_PRODUCT_BOUGHT";

export const DELETE_PRODUCT_LIST_WHEN_ORDERED =
  "DELETE_PRODUCT_LIST_WHEN_ORDERED";
