export const FETCH_PRODUCTS_LIST = "FETCH_PRODUCTS_LIST";

export const GET_PRODUCT_BY_KEY_SEARCH =
  "<GET_PRODUCT_BY_KEY_S></GET_PRODUCT_BY_KEY_S>EARCH";
export const GET_PRODUCT_BY_KEY_SEARCH_SUCCESS =
  "GET_PRODUCT_BY_KEY_SEARCH_SUCCESS";
