export const ADD_A_REVIEW = "ADD_A_REVIEW";
export const ADD_A_REVIEW_SUCCESS = "ADD_A_REVIEW_SUCCESS";

export const GET_REVIEW_OF_PRODUCT = "GET_REVIEW_OF_PRODUCT";
export const GET_REVIEW_OF_PRODUCT_SUCCESS = "GET_REVIEW_OF_PRODUCT_SUCCESS";
